Repository TheBastionBot/Bastion, pull requests merged in 2018-09, with the labels that each got.

#341 README: Fix Typo in Join Bastion HQ
  README.md
Labels: meta

#344 Remove requirement for Cleverbot API key
  commands/guild_admin/chat.js
  handlers/conversationHandler.js
  package.json
  settings/credentials_example.json
Labels: enhancement, semver: minor

#349 Custom avatars for Bastion profile
  changes.json
  commands/info/profile.js
  commands/info/setProfilePicture.js
  data/commands.json
  locales/en_us/command.json
  package.json
  utils/models.js
Labels: Enhancement, SemVer: Major

#350 Bastion Bot v6.17
  changes.json
  handlers/conversationHandler.js
  locales/en/modules.json
  modules/game_stats/ark.js
  modules/guild_admin/chat.js
  package.json
  settings/credentials_example.json
Labels: SemVer: Minor

#353 Bastion Bot v6.17.1
  changes.json
  modules/guild_admin/levelUpRoles.js
  modules/money/roleStore.js
  modules/money/shop.js
  package.json
Labels: SemVer: Patch

#358 data: remove data/.meta file
  data/.meta
Labels: SemVer: Patch

#357 Bastion profile bio should be called profile info
  changes.json
  commands/info/profile.js
  commands/info/setBio.js
  data/commands.json
  locales/en_us/command.json
  locales/en_us/error.json
  package.json
  utils/models.js
Labels: Enhancement, SemVer: Major

#359 fix cat command
  commands/fun/cat.js
Labels: Enhancement, SemVer: Patch

#365 Bastion Bot v6.17.2
  changes.json
  modules/fun/cat.js
  package.json
Labels: SemVer: Patch
