Repository TheBastionBot/Bastion, pull requests merged in 2018-08, with the labels that each got.

#297 Making --server mute able to use a timer
  commands/moderation/textMute.js
Labels: enhancement

#298 Bastion Bot v6.15.1
  changes.json
  events/presenceUpdate.js
  package.json
Labels: semver: patch

#302 Fixing error in getting bio info
  commands/info/profile.js
Labels: enhancement

#301 Adding --module to enableCommand
  changes.json
  commands/guild_admin/enableCommand.js
  package.json
Labels: enhancement

#311 Out of this world stuff, literally!
  changes.json
  commands/fun/apod.js
  data/commands.json
  locales/en_us/command.json
  package.json
  settings/credentials_example.json
Labels: enhancement

#318 Bastion Bot v6.16
  changes.json
  handlers/levelHandler.js
  locales/en/modules.json
  modules/fun/cuddle.js
  modules/fun/hug.js
  modules/fun/kiss.js
  modules/fun/pat.js
  modules/fun/tickle.js
  modules/game_stats/overwatch.js
  modules/moderation/textMute.js
  modules/money/claim.js
  package.json
Labels: semver: minor

#333 Bastion Bot v6.16.1
  changes.json
  handlers/streamNotifier.js
  modules/game_stats/rocketLeague.js
  package.json
Labels: semver: patch
