Repository TheBastionBot/Bastion, pull requests merged in 2018-10, with the labels that each got.

#366 Update & externalize endorsement messages
  commands/fun/echo.js
  commands/fun/selfDestruct.js
  commands/fun/sendEmbed.js
  locales/en_us/info.json
Labels: Enhancement, SemVer: Patch

#370 Pokemon descriptions
  commands/queries/pokemon.js
Labels: Enhancement, SemVer: Patch

#372 feat: Add book command
  changes.json
  commands/queries/book.js
  data/commands.json
  locales/en_us/command.json
  package.json
Labels: Enhancement, SemVer: Minor

#375 Issue 374 show proper message when no one's streaming
  commands/queries/live.js
Labels: Enhancement, SemVer: Patch

#377 Show boot time on startup
  changes.json
  events/ready.js
  package.json
Labels: Enhancement, SemVer: Patch

#379 commands: add world of warcraft command
  changes.json
  commands/game_stats/wow.js
  data/commands.json
  locales/en_us/command.json
  package.json
  settings/credentials_example.json
Labels: Enhancement, SemVer: Minor

#391 Backport wow game stats command #389
  changes.json
  locales/en/modules.json
  modules/game_stats/wow.js
  settings/credentials_example.json
Labels: Enhancement, SemVer: Minor

#393 Bastion Bot v6.18
  changes.json
  locales/en/modules.json
  modules/game_stats/wow.js
  modules/queries/pokemon.js
  package.json
  settings/credentials_example.json
Labels: Enhancement, SemVer: Minor

#395 Easy Settings
  .gitignore
  .travis.yml
  appveyor.yml
  bastion.js
  commands/game_stats/paladins.js
  commands/game_stats/smite.js
  commands/owner/reloadSettings.js
  handlers/webhookHandler.js
  index.js
  methods/getContributors.js
  methods/getPatrons.js
  package.json
  settings/config_example.json
  settings/configurations.example.yaml
  settings/credentials.example.yaml
  settings/credentials_example.json
  tests/boot.js
  utils/models.js
Labels: Enhancement, SemVer: Major

#398 Issue 378 Clash of Clans integration
  commands/game_stats/clashOfClans.js
  data/commands.json
  locales/en_us/command.json
  locales/en_us/error.json
  settings/credentials.example.yaml
Labels: Enhancement, SemVer: Minor

#401 command: add ROT13 command
  commands/queries/rot13.js
  locales/en_us/command.json
Labels: Enhancement, SemVer: Minor

#405 Spoiler Text via ROT13
  commands/queries/rot13.js
  commands/queries/sendSpoiler.js
  commands/queries/showSpoiler.js
  data/commands.json
  events/message.js
  locales/en_us/command.json
  methods/rot13.js
Labels: Enhancement

#406 Spoilers
  changes.json
  commands/fun/sendSpoiler.js
  commands/fun/showSpoiler.js
  commands/queries/rot13.js
  data/Bastion.sqlite
  data/commands.json
  data/playlist.json
  events/message.js
  locales/en_us/command.json
  methods/rot13.js
  package.json
Labels: Enhancement, SemVer: Minor

#407 Decompose events
  events/discord/channelCreate.js
  events/discord/channelDelete.js
  events/discord/channelUpdate.js
  events/discord/error.js
  events/discord/guildBanAdd.js
  events/discord/guildBanRemove.js
  events/discord/guildCreate.js
  events/discord/guildDelete.js
  events/discord/guildMemberAdd.js
  events/discord/guildMemberRemove.js
  events/discord/guildUpdate.js
  events/discord/message.js
  events/discord/messageDelete.js
  events/discord/messageReactionAdd.js
  events/discord/messageReactionRemove.js
  events/discord/messageUpdate.js
  events/discord/presenceUpdate.js
  events/discord/ready.js
  events/discord/roleCreate.js
  events/discord/roleDelete.js
  events/discord/roleUpdate.js
  events/discord/warn.js
  events/self/bastionMissingPermissions.js
  events/self/commandUsage.js
  events/self/moderationLog.js
  events/self/userCredit.js
  events/self/userDebit.js
  events/self/userMissingPermissions.js
  handlers/eventHandler.js
  package.json
Labels: Enhancement, SemVer: Major
