Repository TheBastionBot/Bastion, pull requests merged in 2018-06, with the labels that each got.

#233 discrim command updates
  commands/info/discrim.js
Labels: enhancement

#238 Levelup Toggle
  changes.json
  commands/guild_admin/toggleLevelUps.js
  data/commands.json
  events/message.js
  locales/en_us/command.json
  locales/en_us/info.json
  package.json
Labels: enhancement, release: major

#240 Bastion Bot v6.13.3
  Procfile
  changes.json
  modules/guild_admin/streamerRole.js
  modules/info/discrim.js
  package.json
Labels: release: patch

#243 User Reporting Rewrite
  changes.json
  commands/guild_admin/reportChannel.js
  commands/moderation/report.js
  data/commands.json
  locales/en_us/command.json
  locales/en_us/error.json
  locales/en_us/info.json
  package.json
Labels: enhancement, release: major

#244 Members Only mode
  changes.json
  commands/guild_admin/membersOnly.js
  data/commands.json
  handlers/commandHandler.js
  locales/en_us/command.json
  locales/en_us/info.json
  package.json
  utils/models.js
Labels: enhancement, release: major

#245 Reaction Pinning
  changes.json
  commands/guild_admin/reactionPinning.js
  data/commands.json
  events/messageReactionAdd.js
  events/messageReactionRemove.js
  handlers/eventHandler.js
  locales/en_us/command.json
  locales/en_us/info.json
  package.json
  utils/models.js
Labels: enhancement, release: major

#246 Event Handler Rewrite
  handlers/eventHandler.js
Labels: enhancement, release: patch

#248 Tesseract Integration
  bastion.js
  commands/fun/airhorn.js
  commands/guild_admin/setPrefix.js
  commands/info/stats.js
  commands/music/play.js
  commands/music/summon.js
  commands/owner/reloadSettings.js
  commands/owner/setActivity.js
  commands/owner/setStatus.js
  events/guildMemberAdd.js
  events/guildMemberRemove.js
  events/ready.js
  functions/replaceVariables.js
  handlers/commandHandler.js
  index.js
  package.json
  tests/boot.js
Labels: enhancement, release: major

#249 Bastion Bot v6.13.4
  changes.json
  modules/moderation/report.js
  modules/queries/pokemon.js
  package.json
Labels: release: patch

#252 Remove old Database Implementations
  .gitignore
  bastion.js
  package.json
  tests/boot.js
  utils/populateDatabase.js
  utils/updateDatabase.js
Labels: enhancement, release: major

#253 Multiple Giveaways
  changes.json
  commands/guild_admin/giveaway.js
  commands/money/currencyGiveaway.js
  package.json
Labels: enhancement, semver: major

#261 Reaction Roles
  changes.json
  commands/guild_admin/reactionRolesGroup.js
  commands/guild_admin/roleEmoji.js
  data/commands.json
  events/messageReactionAdd.js
  events/messageReactionRemove.js
  events/ready.js
  handlers/reactionRolesGroupsHandler.js
  locales/en_us/command.json
  locales/en_us/info.json
  utils/models.js
Labels: enhancement, semver: major

#268 AFK Mode
  changes.json
  commands/info/afk.js
  data/commands.json
  events/message.js
  locales/en_us/command.json
  package.json
  utils/models.js
Labels: enhancement, semver: minor
