Repository TheBastionBot/Bastion, pull requests merged in 2019-02, with the labels that each got.

#552 Profile Resetting
  changes.json
  commands/bot_owner/resetDatabase.js
  commands/profile/resetProfile.js
  data/commands.json
  locales/en_us/command.json
Labels: Enhancement, SemVer: Minor

#553 Set giveaway upper time limit to 24
  changes.json
  commands/server_management/giveaway.js
Labels: Enhancement, SemVer: Patch

#556 Patch #555
  changes.json
  commands/productivity/sendSpoiler.js
Labels: Enhancement, SemVer: Patch

#557 Patch disableCommand command
  changes.json
  commands/server_configuration/disableCommand.js
Labels: Enhancement, SemVer: Patch

#559 Bastion Bot v7.1.1
  changes.json
  commands/moderation/addRole.js
  commands/moderation/removeRole.js
  commands/productivity/sendSpoiler.js
  commands/server_configuration/disableCommand.js
  package.json
Labels: SemVer: Patch

#562 Announcement reactions patch
  changes.json
  events/discord/messageReactionAdd.js
Labels: Enhancement, SemVer: Patch

#564 Patch 563
  changes.json
  commands/server_configuration/addWhitelistDomains.js
Labels: Enhancement, SemVer: Patch

#565 Improvements to stats command
  changes.json
  commands/misc/stats.js
Labels: Enhancement, SemVer: Patch

#566 Role/Channel blacklists patch
  changes.json
  handlers/commandHandler.js
Labels: Enhancement, SemVer: Patch

#570 commands: improvements to info commands
  commands/info/roleID.js
Labels: Enhancement, SemVer: Patch

#573 Settings patch
  settings/configurations.example.yaml
  settings/credentials.example.yaml
Labels: Enhancement, SemVer: Patch

#575 Footer disclaimer
  changes.json
  commands/utility/echo.js
Labels: Enhancement, SemVer: Patch

#577 Exclusive roles
  changes.json
  commands/server_configuration/exclusiveRoles.js
  data/commands.json
  locales/en_us/command.json
Labels: Enhancement, SemVer: Minor

#578 Starboard image support
  changes.json
  events/discord/messageReactionAdd.js
Labels: Enhancement, SemVer: Patch

#579 Knock knock?
  changes.json
  handlers/directMessageHandler.js
Labels: Enhancement, SemVer: Minor

#581 Apex Legends Player Stats!
  changes.json
  commands/player_stats/apexLegends.js
  data/commands.json
  locales/en_us/command.json
Labels: Enhancement, SemVer: Minor

#582 Bastion Bot v7.2
  .github/PULL_REQUEST_TEMPLATE.md
  changes.json
  commands/info/roleID.js
  commands/misc/stats.js
  commands/player_stats/apexLegends.js
  commands/server_configuration/addWhitelistDomains.js
  commands/server_configuration/exclusiveRoles.js
  commands/utility/echo.js
  data/commands.json
  events/discord/messageReactionAdd.js
  events/discord/ready.js
  handlers/commandHandler.js
  handlers/directMessageHandler.js
  locales/en_us/command.json
  package.json
  settings/configurations.example.yaml
  settings/credentials.example.yaml
Labels: SemVer: Minor

#584 Karma patch
  changes.json
  commands/profile/reputation.js
Labels: Enhancement, SemVer: Patch

#585 Some changes to instant answers
  changes.json
  handlers/directMessageHandler.js
Labels: Enhancement, SemVer: Patch

#588 Disable sneaky links monitor for bots
  changes.json
  monitors/modules/sneakyLinks.js
Labels: Enhancement, SemVer: Patch
