Repository TheBastionBot/Bastion, pull requests merged in 2022-12, with the labels that each got.

#974 v10.3
  locales/en-US/info.yaml
  package.json
  settings.example.yaml
  src/commands/about.ts
  src/commands/changes.ts
  src/commands/claim.ts
  src/commands/donate.ts
  src/commands/giveaway.ts
  src/commands/iam.ts
  src/commands/invite.ts
  src/commands/leaderboard.ts
  src/commands/lmgtfy.ts
  src/commands/music/pause.ts
  src/commands/music/queue.ts
  src/commands/music/resume.ts
  src/commands/music/skip.ts
  src/commands/music/stop.ts
  src/commands/profile.ts
  src/commands/report.ts
  src/commands/role/delete.ts
  src/commands/role/update.ts
  src/commands/search/anime.ts
  src/commands/search/cryptocurrency.ts
  src/commands/search/definitions.ts
  src/commands/search/game.ts
  src/commands/search/manga.ts
  src/commands/search/movie.ts
  src/commands/search/pokemon.ts
  src/commands/search/redirects.ts
  src/commands/search/tv.ts
  src/commands/search/urbanDictionary.ts
  src/commands/search/wikipedia.ts
  src/commands/server/prune.ts
  src/commands/status.ts
  src/commands/su/eval.ts
  src/commands/su/exec.ts
  src/commands/su/reload.ts
  src/commands/suggest.ts
  src/components/GiveawayEndButton.ts
  src/components/VoiceSessionLockButton.ts
  src/index.ts
  src/listeners/guildCreate.ts
  src/listeners/guildDelete.ts
  src/listeners/messageCreate.ts
  src/listeners/voiceStateUpdate.ts
  src/middlewares/auth.ts
  src/migrate.ts
  src/routes/status.ts
  src/schedulers/giveaways.ts
  src/types.ts
  src/utils/patreon.ts
  src/utils/premium.ts
  src/utils/settings.ts
Labels: Enhancement, SemVer: Minor

#975 v10.4
  locales/en-US/info.yaml
  package.json
  src/bastion.ts
  src/commands/channel/create.ts
  src/commands/config/autoThreads.ts
  src/commands/config/starboard.ts
  src/commands/thread/close.ts
  src/commands/thread/name.ts
  src/listeners/messageCreate.ts
  src/listeners/messageReactionAdd.ts
  src/models/Guild.ts
  src/routes/status.ts
Labels: Enhancement, SemVer: Minor

#976 v10.5
  locales/en-US/info.yaml
  package.json
  src/commands/music/now.ts
  src/commands/music/play.ts
  src/commands/music/queue.ts
  src/components/MusicPausePlayButton.ts
  src/components/MusicSkipButton.ts
  src/components/SelfRolesSelect.ts
  src/listeners/channelUpdate.ts
  src/utils/components.ts
Labels: Enhancement, SemVer: Minor

#977 v10.6
  package.json
  settings.example.yaml
  src/commands/config/autoRoles.ts
  src/commands/config/select-roles/add.ts
  src/commands/config/select-roles/list.ts
  src/commands/config/select-roles/remove.ts
  src/commands/config/selfRoles.ts
  src/commands/iam.ts
  src/commands/music/queue.ts
  src/commands/music/shuffle.ts
  src/commands/role/config.ts
  src/commands/role/info.ts
  src/commands/role/levels.ts
  src/components/SelectRolesButton.ts
  src/components/SelectRolesNoRolesButton.ts
  src/components/SelectRolesSelect.ts
  src/components/SelectRolesUpdateSelect.ts
  src/listeners/guildCreate.ts
  src/listeners/shardResume.ts
  src/models/Role.ts
  src/models/SelectRoleGroup.ts
  src/utils/arrays.ts
  src/utils/buttons.ts
  src/utils/components.ts
  src/utils/constants.ts
  src/utils/premium.ts
Labels: Enhancement, SemVer: Minor

#980 fixed new guild docs not getting created
  src/listeners/guildCreate.ts
Labels: SemVer: Minor

#979 fixed limits for select roles
  src/commands/config/select-roles/add.ts
Labels: SemVer: Minor

#981 v10.6.1
  package.json
  src/commands/config/select-roles/add.ts
  src/listeners/guildCreate.ts
Labels: SemVer: Minor

#978 support relaying DMs via webhooks
  settings.example.yaml
  src/listeners/messageCreate.ts
  src/types.ts
  src/utils/regex.ts
Labels: Enhancement, SemVer: Minor

#982 music: add opus library & error handling
  package.json
  src/commands/music/play.ts
Labels: Enhancement, SemVer: Minor

#984 fix gamification messages not getting disabled
  src/commands/config/gamification.ts
Labels: SemVer: Patch

#985 suggestions: set up voting
  src/commands/suggest.ts
Labels: Enhancement, semver: minor

#988 auto roles can be assigned only to bots (or users)
  src/commands/config/autoRoles.ts
  src/listeners/guildMemberAdd.ts
  src/models/Role.ts
Labels: semver: minor
