Repository TheBastionBot/Bastion, pull requests merged in 2023-01, with the labels that each got.

#991 change suggestion status after it has been accepted/rejected
  src/components/SuggestionAcceptButton.ts
  src/components/SuggestionRejectButton.ts
Labels: Enhancement, semver: minor

#990 Gamification: custom level up channel
  src/commands/config/gamification.ts
  src/listeners/messageCreate.ts
  src/models/Guild.ts
Labels: Enhancement, semver: minor

#993 Fix: level up removed other roles
  src/listeners/messageCreate.ts
Labels: semver: patch

#994 add option to remove user infractions
  src/commands/user/infractions.ts
Labels: Enhancement, semver: minor

#995 more events for mod logs
  src/commands/warn.ts
  src/components/UserReportBanButton.ts
  src/components/UserReportKickButton.ts
  src/components/UserReportTimeoutButton.ts
Labels: Enhancement, semver: minor

#996 chore: linting
  src/bastion.ts
  src/commands/config/autoRoles.ts
  src/commands/config/selfRoles.ts
  src/commands/gamestats/aimlab.ts
  src/commands/message/clear.ts
  src/commands/search/definitions.ts
  src/components/SelectRolesSelect.ts
  src/components/SelfRolesClearButton.ts
  src/components/SelfRolesSelect.ts
  src/index.ts
  src/listeners/guildCreate.ts
  src/listeners/guildMemberAdd.ts
  src/listeners/messageCreate.ts
  src/listeners/ready.ts
  src/migrate.ts
  src/utils/arrays.ts
  src/utils/members.ts
Labels: semver: patch

#1001 embeds: fix validator
  src/utils/embeds.ts
Labels: semver: patch

#1003 show user status, timeout & voice channel info
  src/commands/user/info.ts
  src/utils/members.ts
Labels: Enhancement, semver: minor

#1004 meta: update repo docs & actions
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/DEVELOPMENT_ENVIRONMENT.md
  .github/FUNDING.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/SECURITY.md
  .github/SUPPORT.md
  .github/TESTING.md
  .github/atlanna.yml
  .github/workflows/nodejs.yml
Labels: GitHub

#1005 show message content in messageDelete & messageUpdate event logs (opt-in)
  .gitignore
  src/commands/config/log.ts
  src/commands/config/logs/content.ts
  src/commands/config/logs/mod.ts
  src/commands/config/logs/server.ts
  src/commands/server/info.ts
  src/listeners/messageDelete.ts
  src/listeners/messageUpdate.ts
  src/models/Guild.ts
Labels: Enhancement, semver: minor

#1006 add `give` command to give/take coins & xp from an user
  locales/en-US/info.yaml
  src/commands/give.ts
  src/utils/members.ts
Labels: Enhancement, semver: minor

#1007 use `updateExperience` for updating xp & remove `await` from `updateBalance` calls
  src/commands/claim.ts
  src/listeners/messageCreate.ts
Labels: semver: patch

#1008 fix cases where `Roles#set` can have duplicate role IDs
  src/components/SelectRolesSelect.ts
  src/components/SelfRolesSelect.ts
  src/listeners/messageCreate.ts
Labels: semver: patch

#1009 v10.8
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/DEVELOPMENT_ENVIRONMENT.md
  .github/FUNDING.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/SECURITY.md
  .github/SUPPORT.md
  .github/TESTING.md
  .github/atlanna.yml
  .github/workflows/nodejs.yml
  .gitignore
  commands.json
  locales/en-US/info.yaml
  package.json
  src/commands/claim.ts
  src/commands/config/log.ts
  src/commands/config/logs/content.ts
  src/commands/config/logs/mod.ts
  src/commands/config/logs/server.ts
  src/commands/config/select-roles/add.ts
  src/commands/give.ts
  src/commands/server/info.ts
  src/commands/user/info.ts
  src/components/SelectRolesSelect.ts
  src/components/SelectRolesUpdateSelect.ts
  src/components/SelfRolesSelect.ts
  src/listeners/messageCreate.ts
  src/listeners/messageDelete.ts
  src/listeners/messageUpdate.ts
  src/models/Guild.ts
  src/utils/embeds.ts
  src/utils/members.ts
Labels: semver: minor

#1010 Fix permissions for `/role config` command
  package.json
  src/commands/role/config.ts
Labels: semver: patch

#1012 locales: localize more strings
  locales/en-US/info.yaml
  src/commands/channel/create.ts
  src/commands/channel/delete.ts
  src/commands/channel/update.ts
  src/commands/comic/phd.ts
  src/commands/emoji/info.ts
  src/commands/games/8ball.ts
  src/commands/games/roll.ts
  src/commands/invite.ts
  src/commands/message/clear.ts
  src/commands/warn.ts
Labels: semver: patch

#1013 v10.8.1
  locales/en-US/info.yaml
  package.json
  src/commands/channel/create.ts
  src/commands/channel/delete.ts
  src/commands/channel/update.ts
  src/commands/comic/phd.ts
  src/commands/emoji/info.ts
  src/commands/games/8ball.ts
  src/commands/games/roll.ts
  src/commands/invite.ts
  src/commands/message/clear.ts
  src/commands/role/config.ts
  src/commands/warn.ts
Labels: semver: patch

#1014 build & push docker image on release
  .github/workflows/docker-publish.yml
  Dockerfile
  settings.example.yaml
Labels: Enhancement, CI, platform: Docker

#1015 escape markdown in twitch usernames
  settings.example.yaml
  src/commands/config/liveStreams.ts
Labels: Enhancement, semver: patch
